[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lop"
version = "1.0.0"

[tool.setuptools.packages.find]
include = ["lop*"]
namespaces = true
